// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicgJIs9rYtvqU3WVD6StNW6F8L9eCO_g',
    appId: '1:841934933765:web:f5f43a78bc34d02f03b16c',
    messagingSenderId: '841934933765',
    projectId: 'overflowai',
    authDomain: 'overflowai.firebaseapp.com',
    storageBucket: 'overflowai.firebasestorage.app',
    measurementId: 'G-DPZDSHCF3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlivR_OKfQiNCNUtdOITA9FUMBZgnBZ1A',
    appId: '1:841934933765:android:aa4dcbeae7e881d603b16c',
    messagingSenderId: '841934933765',
    projectId: 'overflowai',
    storageBucket: 'overflowai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDw4ti6apbt_R2mWLOXSuNRCBIVMpYddY',
    appId: '1:841934933765:ios:82a2c8500b25c31a03b16c',
    messagingSenderId: '841934933765',
    projectId: 'overflowai',
    storageBucket: 'overflowai.firebasestorage.app',
    iosClientId: '841934933765-mktkn0t6s82137ppem3kaqtjkcikte28.apps.googleusercontent.com',
    iosBundleId: 'com.example.overflowAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDw4ti6apbt_R2mWLOXSuNRCBIVMpYddY',
    appId: '1:841934933765:ios:82a2c8500b25c31a03b16c',
    messagingSenderId: '841934933765',
    projectId: 'overflowai',
    storageBucket: 'overflowai.firebasestorage.app',
    iosClientId: '841934933765-mktkn0t6s82137ppem3kaqtjkcikte28.apps.googleusercontent.com',
    iosBundleId: 'com.example.overflowAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCicgJIs9rYtvqU3WVD6StNW6F8L9eCO_g',
    appId: '1:841934933765:web:722934420fbdd75803b16c',
    messagingSenderId: '841934933765',
    projectId: 'overflowai',
    authDomain: 'overflowai.firebaseapp.com',
    storageBucket: 'overflowai.firebasestorage.app',
    measurementId: 'G-BSMELPMFC4',
  );
}
